### ISSUE TITLE
Stratum authentication failed

### ISSUE THREAD

**Issue by ottomatias** [zone117x/node-cryptonote-pool#103]
I can't seem to get authenticated when connecting with minerd 
`/minerd -a cryptonight -o stratum+tcp://xxx.com:3333 -u 495fgzxjCotA89KGYs9Z1vchd222N4qUnUXwaTLHxG1Sizh2FqjQp3yYTY2h5BndF7LGiFjYBNNxvEDYx1m3jxYqJqDt222 -p x`
It answers alright because if I'm not running Node it says connection refused but what is wrong with the authentication? I've tried different Monero addresses but with no help.

**Comment by cibermax** [comment]
Any news??
