### ISSUE TITLE
Front-end Loading forever...

### ISSUE THREAD

**Issue by gaffelosked** [zone117x/node-cryptonote-pool#120]
Hello, I'm experiencing some difficulties with this software. The front end website just loads forever with that spinning animation and I've got all the files in the right place.

**Comment by frankmusher** [comment]
Did you fix this?

**Comment by bapparabi** [comment]
this may be because either the api link is not correct or the website files i corrupted ..just uplaod the website file again and it will work fine ..if you modifying any file use it any correct php file editor then the file will not corrupt
