### ISSUE TITLE
node-cryptonote-util must be updated to be RCT aware

### ISSUE THREAD

**Issue by sammy007** [zone117x/node-cryptonote-pool#130]
Lucasjone's version is pretty outdated, latest monero changes requires change to `node-cryptonote-util` package.

**Comment by zone117x** [comment]
@sammy007 Can you take a look at https://github.com/zone117x/node-cryptonote-util and confirm this is fixed?

**Comment by sammy007** [comment]
I am not running any pool and have no environment for testing it, better ask for confirmation from an active pool admin.

**Comment by zone117x** [comment]
I think this should all be good now.
