### ISSUE TITLE
npm update failed ringct/rctTypes.h

### ISSUE THREAD

**Issue by dzevadhadzic** [zone117x/node-cryptonote-pool#133]
It seems it can't find ringct include..
/xmr/pool# npm update

> cryptonote-util@0.0.1 install /home/user/xmr/pool/node_modules/cryptonote-util
> node-gyp rebuild

make: Entering directory '/home/user/xmr/pool/node_modules/cryptonote-util/build'
  CXX(target) Release/obj.target/cryptonote/src/main.o
In file included from ../src/main.cc:7:0:
../src/cryptonote_core/cryptonote_basic.h:26:29: fatal error: ringct/rctTypes.h: No such file or directory
compilation terminated.
cryptonote.target.mk:103: recipe for target 'Release/obj.target/cryptonote/src/main.o' failed
make: *** [Release/obj.target/cryptonote/src/main.o] Error 1
make: Leaving directory '/home/user/xmr/pool/node_modules/cryptonote-util/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-59-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/xmr/pool/node_modules/cryptonote-util
gyp ERR! node -v v7.4.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
cryptonote-pool@0.0.1 /home/user/xmr/pool
â””â”€â”€ multi-hashing@0.0.9  (git://github.com/zone117x/node-multi-hashing.git#73996fe77104108f2d66ef750b3e1bce42e4d8f0)

npm ERR! Linux 4.4.0-59-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "update"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! cryptonote-util@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cryptonote-util@0.0.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cryptonote-util package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cryptonote-util
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cryptonote-util
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/xmr/pool/npm-debug.log

**Comment by zone117x** [comment]
Looks like a file was missing from a recent pull request to support monero's rct hardfork. I just committed this: https://github.com/zone117x/node-cryptonote-util/commit/7678a9138775b51119a29b560f55dabc2ae57867
Try again and let me know if it works.

**Comment by zone117x** [comment]
Assuming this is fixed now and closing ticket
