### ISSUE TITLE
Invalid API call

### ISSUE THREAD

**Issue by Mark20039** [zone117x/node-cryptonote-pool#136]
I can successfully run the pool (it shows no errors) but the API calls are not working. When i visit the website using API call port (8177) it just shows Invalid API call. If i try to search a monero address on the website it doesn't display the balance, it just loads indefinitely. Console is outputting 0 visitors and 0 address searches. I am using node v0.10.36 and nmp version 1.4.28
In the config file for the website i set the API variable to "myip:8177" and the poolHost variable  to "myip". I know the same port is used on the pool config because if i don't run the pool i get unknown page instead of Invalid API Call.
If you need any more information just ask. Thanks in advance!

**Comment by Mark20039** [comment]
Fixed it.

**Comment by frankmusher** [comment]
How did you fix it?

**Comment by n0bility6** [comment]
Hi, How did you fix it?
