### ISSUE TITLE
many npm update errors

### ISSUE THREAD

**Issue by daveinli** [zone117x/node-cryptonote-pool#137]
make: *** [Release/obj.target/multihashing/multihashing.o] Error 1
make: Leaving directory `/root/pool/node_modules/multi-hashing/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v0.12.18/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1078:12)
gyp ERR! System Linux 2.6.32-042stab106.6
gyp ERR! command "node" "/root/.nvm/versions/node/v0.12.18/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/pool/node_modules/multi-hashing
gyp ERR! node -v v0.12.18
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Linux 2.6.32-042stab106.6
npm ERR! argv "/root/.nvm/versions/node/v0.12.18/bin/node" "/root/.nvm/versions/node/v0.12.18/bin/npm" "update"
npm ERR! node v0.12.18
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! cryptonote-util@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cryptonote-util@0.0.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the cryptonote-util package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cryptonote-util
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls cryptonote-util
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/pool/npm-debug.log
root@server [~/pool]#

**Comment by daveinli** [comment]
anyone interested in building this for me on a clean install.
let me know, ready to give up

thanks

**Comment by Snipa22** [comment]
If you need help, I'm able to provide some assistance with this.  Find me on IRC, Snipa, irc.freenode.net in #monero-pools.

**Comment by Aleix-Oto** [comment]
im on IRC channel but it's empty....

**Comment by daveinli** [comment]
if anyone wants to build me out a site let me know. 
I will pay obviously. I have a nice XMR domain name and hosting with root access.
email me at dave@dafmarketing.com
looking to make this be the leading site for Monero

**Comment by zone117x** [comment]
@Snipa22 Is this just caused by a Node update/change in native module building?

**Comment by Snipa22** [comment]
I suspect this is because he's missing boost libs or something along those lines. You must be able to build monerod, which isn't touched on super-well in the readme.

**Comment by daveinli** [comment]
fixed the issues above, redid everything on an ubuntu server and up and running.
now have an error when test connecting a miner, stratum Authentication Failed.
clueless to why this is happening. my site is XMRMining.com if someone has a clue to why please let me know. thank you for your continued support

**Comment by daveinli** [comment]
I updated the hard fork and now getting this error.
stratum_recv_line failed
