### ISSUE TITLE
 Stratum authentication failed

### ISSUE THREAD

**Issue by upggr** [zone117x/node-cryptonote-pool#139]
I have made a custom coin, fork of cryptonote. this application seems to work ok and connects to the coin daemon and the wallet, but when I use minerd i get the error :  Stratum authentication failed

my coin has a 95 characters address and all. why is this happening and how to fix it if it is not a bug ?

**Comment by upggr** [comment]
looks like if i comment the login check in pool.js problem is solved, but that cant be right..

**Comment by chaturanga50** [comment]
as i see, this issue coming due hard fork update, update your package.json with following,

`"cryptonote-util": "git://github.com/M5M400/node-cryptonote-util.git#xmr-Nan-2.0"`

and remove node_modules and run npm update

**Comment by upggr** [comment]
thank you, that fixed it.

**Comment by zone117x** [comment]
Are you guys having issues with getting the pool to work with XMR or altcoins?

**Comment by upggr** [comment]
A custom coin I ve made, XMD xmdcoin.com
