### ISSUE TITLE
miners not connecting to pool

### ISSUE THREAD

**Issue by daveinli** [zone117x/node-cryptonote-pool#141]
after many other issues, site is running.
on windows it shows like it is connecting and hashes using ccminer and cryptonote, but on site not showing connections.
on the admin it shows 2 registered address but no stats for them

on a mining rig running latest ethosdistro and sgminer 5.5.5 it will not connect to my pool, just hangs up on *using Jannson . when i switch rig back to pool.minexmr.com it runs perfectly. can not understand what is wrong.

my site is xmrmining.com and pool.xmrmining.com is the front end
any ideas, my linux guy and I are clueless at this point.

**Comment by CanadianRepublican** [comment]
this seems like the problems I was having..

https://github.com/zone117x/node-cryptonote-pool/issues/107   <-- apparently its fixed

**Comment by daveinli** [comment]
yes problem fixed, turns out the miners were configured with worker id's
