### ISSUE TITLE
Error polling getblocktemplate {"code":"EC ONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}

### ISSUE THREAD

**Issue by ub14** [zone117x/node-cryptonote-pool#149]
Hi,

I have this error for run bytecoin node

root@ub14:~/pool# node init.js
2015-08-31 00:07:44 [master] Pool spawned on 6 thread(s)
2015-08-31 00:07:44 [charts] Started
2015-08-31 00:07:44 [chartsDataCollector] Started
2015-08-31 00:07:44 [pool] (Thread 3) Error polling getblocktemplate {"code":"EC ONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}
2015-08-31 00:07:44 [pool] (Thread 3) Could not start pool
2015-08-31 00:07:44 [charts] Started
2015-08-31 00:07:44 [api] API started & listening on port 8117
2015-08-31 00:07:44 [api] Error getting daemon data {"code":"ECONNREFUSED","errn o":"ECONNREFUSED","syscall":"connect"}
2015-08-31 00:07:44 [api] Stat collection finished: NaN ms redis, 20 ms daemon
2015-08-31 00:07:44 [api] Error collecting all stats
2015-08-31 00:07:44 [payments] Started
2015-08-31 00:07:44 [payments] No workers' balances reached the minimum payment threshold
2015-08-31 00:07:44 [unlocker] Started
2015-08-31 00:07:44 [unlocker] No blocks candidates in redis
2015-08-31 00:07:44 [pool] (Thread 1) Error polling getblocktemplate {"code":"EC ONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}
2015-08-31 00:07:44 [pool] (Thread 1) Could not start pool
2015-08-31 00:07:45 [pool] (Thread 6) Error polling getblocktemplate {"code":"EC ONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}
2015-08-31 00:07:45 [pool] (Thread 6) Could not start pool

my config:

`{
    "coin": "bytecoin",
    "symbol": "BCN",

    "logging": {
        "files": {
            "level": "info",
            "directory": "logs",
            "flushInterval": 5
        },
        "console": {
            "level": "info",
            "colors": true
        }
    },

    "poolServer": {
        "enabled": true,
        "clusterForks": "auto",
        "poolAddress": "25LMwJUw34WA6455YBw3wEJrjq46scSLCBqSdk3npE77cjhFgf5DbvJZCfwt2Tm3Sdw4SbV54t5456xmeG5mLWLxBBb",
        "blockRefreshInterval": 1000,
        "minerTimeout": 900,
        "ports": [
            {
                "port": 3333,
                "difficulty": 100,
                "desc": "Low end hardware"
            },
            {
                "port": 5555,
                "difficulty": 2000,
                "desc": "Mid range hardware"
            },
            {
                "port": 7777,
                "difficulty": 10000,
                "desc": "High end hardware"
            },
            {
                "port": 8888,
                "difficulty": 10000,
                "desc": "Hidden port",
                "hidden": true
            }
        ],
        "varDiff": {
            "minDiff": 2,
            "maxDiff": 100000,
            "targetTime": 100,
            "retargetTime": 30,
            "variancePercent": 30,
            "maxJump": 100
        },
        "shareTrust": {
            "enabled": true,
            "min": 10,
            "stepDown": 3,
            "threshold": 10,
            "penalty": 30
        },
        "banning": {
            "enabled": true,
            "time": 600,
            "invalidPercent": 25,
            "checkThreshold": 30
        },
        "slushMining": {
            "enabled": false,
            "weight": 120,
            "blockTime": 60,
            "lastBlockCheckRate": 1
        }
    },

    "payments": {
        "enabled": true,
        "interval": 600,
        "maxAddresses": 50,
        "mixin": 3,
        "transferFee": 5000000000,
        "minPayment": 100000000000,
        "denomination": 100000000000
    },

    "blockUnlocker": {
        "enabled": true,
        "interval": 30,
        "depth": 60
    },

    "api": {
        "enabled": true,
        "hashrateWindow": 600,
        "updateInterval": 5,
        "port": 8117,
        "blocks": 30,
        "payments": 30,
        "password": ""
    },

    "daemon": {
        "host": "127.0.0.1",
        "port": 8085
    },

    "wallet": {
        "host": "127.0.0.1",
        "port": 8087
    },

    "redis": {
        "host": "127.0.0.1",
        "port": 8090,
        "auth": null
    }
} `

Pls help me!

--------------------------------

i make daemon and simplewallet - port default. no error.

**Comment by n0bility6** [comment]
Hi same problem here.

**Comment by ub14** [comment]
Hi!
It's error when not work daemon and wallet. This happens when you incorrectly expose your ports. You must first check the default values. If you use a virtual machine on Windows (daemon, wallet) - Ubuntu (node), then you must assign IP: 0.0.0.0, and not 127.0.0.1.

My config:

(WINDOWS) IP - 10.0.0.100
(UBUNTU) IP - 10.0.0.200

(WINDOWS) bytecoind.conf

```
 rpc-bind-ip=0.0.0.0
 rpc-bind-port=41085
 p2p-bind-ip=127.0.0.1
 p2p-bind-port=41089
 p2p-external-port=41900
```

(WINDOWS) bytecoind.bat

```
bytecoind --data-dir d:\XXXXXXXXXX\Apps/bytecoind --config-file d:\XXXXXXXXX\bytecoin-daemon-windows\bytecoind.conf

pause
```

(WINDOWS) wallet.bat

```
simplewallet --wallet-file bytecoind.wallet --password YOUR-PASSWORD-WALLET --rpc-bind-ip 0.0.0.0 --rpc-bind-port 41087 --daemon-port 41085

pause 
```

(UBUNTU) node: config.json

```
    "daemon": {
        "host": "10.0.0.100",
        "port": 41085
    },

    "wallet": {
        "host": "10.0.0.100",
        "port": 41087
    },

    "redis": {
        "host": "10.0.0.100",
        "port": 6379,
        "auth": null
    }
```

**Comment by igalfsg** [comment]
@ub14 I tried your solution but it's not the same IP addresses for mine (I guess since it didn't work) is there a way to see what adrdresses my services are running?

**Comment by isbkch** [comment]
How did you find your correct IPs

**Comment by lxmolo** [comment]
@ub14  (WINDOWS) bytecoind.conf，   (WINDOWS) bytecoind.bat，  (WINDOWS) wallet.bat   Where are these documents? What service do I need to install, software? Not very familiar with these.
Also，simplewallet --wallet-file=example_wallet.bin --pass=12345 --rpc-bind-port=8082   and  bytecoind --rpc-bind-ip=0.0.0.0 --rpc-bind-port=8081 Where to run？thanks,thanks....
