### ISSUE TITLE
Failed to parse block

### ISSUE THREAD

**Issue by dinho-afsn** [zone117x/node-cryptonote-pool#176]
Error: Failed to parse block
    at Object.BlockTemplate.nextBlob (/var/www/poolafsn/lib/pool.js:120:23)
    at Object.Miner.getJob (/var/www/poolafsn/lib/pool.js:297:41)
    at handleMinerMethod (/var/www/poolafsn/lib/pool.js:492:28)
    at handleMessage (/var/www/poolafsn/lib/pool.js:606:13)
    at Socket.socket.on.on.on.pushMessage (/var/www/poolafsn/lib/pool.js:660:25)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)

2017-07-22 14:46:25 [master] Pool fork 1 died, spawning replacement worker...
2017-07-22 14:46:26 [api] Stat collection finished: 3 ms redis, 4 ms daemon
2017-07-22 14:46:26 [api] Broadcasting to 0 visitors and 0 address lookups
2017-07-22 14:46:27 [pool] (Thread 1) New block to mine at height 1315000 w/ difficulty of 427448662
2017-07-22 14:46:27 [pool] (Thread 1) Started server listening on port 3333

how to solve?

**Comment by d3ancole1995** [comment]
same issue

**Comment by gjnardoni** [comment]
Same happens to me with XDN, monero works fine :D O_O
https://github.com/fancoder/cryptonote-universal-pool/issues/41

**Comment by dinho-afsn** [comment]
Solve it cryptonote-util fork-note

**Comment by d3ancole1995** [comment]
Do you have a link for that?

**Comment by dinho-afsn** [comment]
Replace in your package.json 
"cryptonote-util": "git://github.com/forknote/node-cryptonote-util.git"

**Comment by dinho-afsn** [comment]
Is your pool sending payments?
Mine is with this problem of sending payments, if you know of someone who corrected and can notify thanks.

**Comment by d3ancole1995** [comment]
I have got pool working in another way. Modifying that repo then compiling. What errors do you get when it tries to send payment? Transactions are sending fine 👍

**Comment by dinho-afsn** [comment]
No mistake, I just do not get anything. no log erros only
2017-08-09 21:19:38 No workers' balances reached the minimum payment threshold
Would it be too much to ask you for a zip from your pool?
Check out my pool
http://173.212.244.109/#

My pool is in Brazil so I will not be your competitor. LOL
But if you can help me. Thank you so much

**Comment by dinho-afsn** [comment]
My email is dinho.afsn@gmail.com if you can send me the pool in zip, I would run it now to see if I receive payments as well. Here I left a week and I did not receive anything, now I have re-done and I'm testing again

**Comment by d3ancole1995** [comment]
My pool is for another coin (my own that I will be launching soon). I can't zip because source is in work office on development server. No access from home

You should check the config file the minimum payment threshholds

**Comment by d3ancole1995** [comment]
Recommend you also check coinUnits var in config files

**Comment by gjnardoni** [comment]
What is your error sending payments?. 
Can you post your log please?

**Comment by dinho-afsn** [comment]
I've already downloaded the minimum amount for withdrawal and it's no use the pool does not send payment
I'll get the logs.

**Comment by dinho-afsn** [comment]
Payments Log:
2017-08-08 22:08:33 Started
2017-08-08 22:08:33 No workers' balances reached the minimum payment threshold
2017-08-09 19:30:00 Started
2017-08-09 19:30:00 No workers' balances reached the minimum payment threshold
2017-08-09 19:40:00 Started
2017-08-09 19:40:00 No workers' balances reached the minimum payment threshold
2017-08-09 19:49:21 Started
2017-08-09 19:49:21 No workers' balances reached the minimum payment threshold
2017-08-09 19:50:04 Started
2017-08-09 19:50:04 No workers' balances reached the minimum payment threshold
2017-08-09 20:00:04 No workers' balances reached the minimum payment threshold
2017-08-09 20:10:04 No workers' balances reached the minimum payment threshold
2017-08-09 20:20:04 No workers' balances reached the minimum payment threshold
2017-08-09 20:30:04 No workers' balances reached the minimum payment threshold
2017-08-09 20:40:04 No workers' balances reached the minimum payment threshold
2017-08-09 20:50:04 No workers' balances reached the minimum payment threshold
2017-08-09 21:00:04 No workers' balances reached the minimum payment threshold
2017-08-09 21:09:08 Started
2017-08-09 21:09:08 No workers' balances reached the minimum payment threshold
2017-08-09 21:09:38 Started
2017-08-09 21:09:38 No workers' balances reached the minimum payment threshold
2017-08-09 21:19:38 No workers' balances reached the minimum payment threshold

Master Log:

2017-08-08 22:08:33 Pool spawned on 4 thread(s)
2017-08-09 19:29:59 Pool spawned on 4 thread(s)
2017-08-09 19:40:00 Pool spawned on 4 thread(s)
2017-08-09 19:49:21 Pool spawned on 4 thread(s)
2017-08-09 19:50:03 Pool spawned on 4 thread(s)
2017-08-09 21:09:08 Pool spawned on 4 thread(s)
2017-08-09 21:09:38 Pool spawned on 4 thread(s)

There are no errors in the logs.
The miners get miners can mine normally, the daemon is running, I opened the wallet rpc with parameters:
./monero-wallet-rpc --disable-rpc-login --trusted-daemon --rpc-bind-port 18082 --wallet-file xmr-wallet

All right, but do not make payments.
So I asked about the zip, because I just wanted to see your package.json to know what versions of libs you are using

**Comment by dinho-afsn** [comment]
Pool config.json

{
    "coin": "monero",
    "symbol": "XMR",

    "logging": {
        "files": {
            "level": "info",
            "directory": "logs",
            "flushInterval": 5
        },
        "console": {
            "level": "info",
            "colors": true
        }
    },

    "poolServer": {
        "enabled": true,
        "clusterForks": "auto",
        "poolAddress": "mywalletaddress",
        "blockRefreshInterval": 1000,
        "minerTimeout": 900,
        "ports": [
            {
                "port": 3333,
                "difficulty": 100,
                "desc": "Low end hardware"
            },
            {
                "port": 5555,
                "difficulty": 2000,
                "desc": "Mid range hardware"
            },
            {
                "port": 7777,
                "difficulty": 10000,
                "desc": "High end hardware"
            },
            {
                "port": 8888,
                "difficulty": 10000,
                "desc": "Hidden port",
                "hidden": true
            }
        ],
        "varDiff": {
            "minDiff": 2,
            "maxDiff": 100000,
            "targetTime": 100,
            "retargetTime": 30,
            "variancePercent": 30,
            "maxJump": 100
        },
        "shareTrust": {
            "enabled": true,
            "min": 10,
            "stepDown": 3,
            "threshold": 10,
            "penalty": 30
        },
        "banning": {
            "enabled": true,
            "time": 600,
            "invalidPercent": 25,
            "checkThreshold": 30
        },
        "slushMining": {
            "enabled": false,
            "weight": 300,
            "blockTime": 60,
            "lastBlockCheckRate": 1
        }
    },

    "payments": {
        "enabled": true,
        "interval": 600,
        "maxAddresses": 50,
        "mixin": 3,
        "transferFee": 50000000,
        "minPayment": 10000000000,
        "denomination": 10000000000
    },

    "blockUnlocker": {
        "enabled": true,
        "interval": 30,
        "depth": 60,
        "poolFee": 1,
        "devDonation": 0,
        "coreDevDonation": 0
    },

    "api": {
        "enabled": true,
        "hashrateWindow": 600,
        "updateInterval": 5,
        "port": 8117,
        "blocks": 30,
        "payments": 30,
        "password": "xxxxxxxx"
    },

    "daemon": {
        "host": "127.0.0.1",
        "port": 18081
    },

    "wallet": {
        "host": "127.0.0.1",
        "port": 18082
    },

    "redis": {
        "host": "127.0.0.1",
        "port": 6379,
        "auth": null
    }
}

**Comment by dinho-afsn** [comment]
Coin units is: 
var coinUnits = 1000000000000;

**Comment by dinho-afsn** [comment]
See nothing changes in
  Pending Balance: 0.000000000000 XMR
  Total Paid: 0.000000000000 XMR

I came to leave a week mining with 4.5 kH / s and remained zero. I have now redone the server and am testing, but it still does not change the pending

**Comment by d3ancole1995** [comment]
I would say its your "minPayment" in that config.json

Download redis-desktop

Connect to the redis server and look under "workers"

See what is their balance and if it reached that much

**Comment by dinho-afsn** [comment]
http://173.212.244.109/#payments
0.001 XMR

I'm going to download the redis desktop now and see what happens, thanks for the tip

**Comment by dinho-afsn** [comment]
See the hashs being sent from this miner here:
43uzxFVBgnFVDddCqp3MP24R69aEPBrCqERL8RpUy5uGhBmYsjnZr2vDrDCFVKaqak9Tt3XYWBkrNUHxuPt7AuVa6qWqMJc

Copy and paste into stats

**Comment by dinho-afsn** [comment]
Does anyone have the cryptonote pool running?

**Comment by d3ancole1995** [comment]
@dinho-afsn I've dropped you an email

**Comment by gjnardoni** [comment]
Correct me but you don't have any block unlocked to pay by
http://173.212.244.109/#pool_blocks

**Comment by dinho-afsn** [comment]
Not now, but stayed 4 days with 4.5 kh / s in Bytecoin, got to break 4 blocks but none of them appeared here. So I think the problem is in the pool and not in the coins.

**Comment by gjnardoni** [comment]
but they need to mature until get unlocked. Maturity Depth Requirement: 60
So you have to break 61 blocks until the first one get unlocked. 
At least I understand (I also did an experiment with a brand new coin to a better understanding).
Am I wrong?

**Comment by gjnardoni** [comment]
BTW this parameters is in source code.

**Comment by dinho-afsn** [comment]
Look, I hope you're right, thinking so I think you might be right.

**Comment by dinho-afsn** [comment]
Look, I hope you're right, thinking so I think you might be right.
He had not noticed about maturity. I'm going to put the BCN pool again now that I already had 4 completed blocks and try to close the 6 missing ones.
Your information was very valuable!
Thank you very much I will direct all hashing power to finish testing

**Comment by gjnardoni** [comment]
Can you tell me how much power hashes do you have to break a block and how long did you take?. Just to have something to compare with. You've said it was BCN right?

**Comment by dinho-afsn** [comment]
4 kh / s 1 day or less in BCN

**Comment by gjnardoni** [comment]
tnx

**Comment by freemanjackal** [comment]
for those with the payment problem("No worker 's balance have reached..."), in my humble opinion the problem is in the blockunlocker module in lib folder, this is the one who handle and update balance in db according to the shares, and it is not working properly. it set old the block as orphans so it does update the db accordingly due to it is comcomparing blocks nad header hash from differents heights. i hope this may help someone out there...

**Comment by coinmyth** [comment]
it was working almost fine, but now i cant connect to the pool, it is just spawning 1 thread,it were 4, but now just 1 and it is not letting me connect,i have donde almost anything, there is no error log report, just can´t connect, any suggestion???

**Comment by minereobot1** [comment]
> Same happens to me with XDN, monero works fine :D O_O
> [fancoder#41](https://github.com/fancoder/cryptonote-universal-pool/issues/41)

callate marica no te funciona nada porque eres un puto marica gay
