### ISSUE TITLE
Page doesnt loading correctly

### ISSUE THREAD

**Issue by mk148a** [zone117x/node-cryptonote-pool#177]
Hi, i use your pool on my localhost.
I use ubuntu-14.04.5-server-amd64 , my configuration is here:

nano config.json
  GNU nano 2.2.6            File: config.json
```

{
    "coin": "AEON",
    "symbol": "AEON",

    "logging": {
        "files": {
            "level": "info",
            "directory": "logs",
            "flushInterval": 5
        },
        "console": {
            "level": "info",
            "colors": true
        }
    },

    "poolServer": {
        "enabled": true,
        "clusterForks": "auto",
        "poolAddress": "WmsooNi3zd4NBYGEB8F5hyJutSHa5KLdKgQtgDr5bowCecViJLWmqJB$
        "blockRefreshInterval": 1000,
        "minerTimeout": 900,
       "ports": [
            {
                "port": 3333,
                "difficulty": 100,
                "desc": "Low end hardware"
            },
            {
                "port": 5555,
                "difficulty": 2000,
                "desc": "Mid range hardware"
            },
            {
                "port": 7777,
                "difficulty": 10000,
                "desc": "High end hardware"
            },
            {
                "port": 8888,
                "difficulty": 10000,
                "desc": "Hidden port",
                "hidden": true
            }
        ],
        "varDiff": {
            "minDiff": 2,
            "maxDiff": 100000,
            "targetTime": 100,
            "retargetTime": 30,
            "variancePercent": 30,
            "maxJump": 100
        },
        "shareTrust": {
            "enabled": true,
            "min": 10,
            "stepDown": 3,
            "threshold": 10,
            "penalty": 30  },
        "banning": {
            "enabled": true,
            "time": 600,
            "invalidPercent": 25,
            "checkThreshold": 30
        },
        "slushMining": {
            "enabled": false,
            "weight": 300, 
"blockTime": 60,
            "lastBlockCheckRate": 1
        }
    },

    "payments": {
        "enabled": true,
        "interval": 600,
        "maxAddresses": 50,
        "mixin": 3,
 "transferFee": 5000000000,
        "minPayment": 100000000000,
        "denomination": 100000000000
    },

    "blockUnlocker": {
        "enabled": true,
        "interval": 30,
        "depth": 60,
        "poolFee": 2,
  "devDonation": 0.1,
        "coreDevDonation": 0.1
    },

    "api": {
        "enabled": true,
        "hashrateWindow": 600,
        "updateInterval": 5,
        "port": 8117,
        "blocks": 30,
  "payments": 30,
        "password": "148150"
    },

    "daemon": {
        "host": "192.168.31.5",
        "port": 9998
    },

    "wallet": {
 "host": "192.168.31.5",
        "port": 8082
    },

    "redis": {
        "host": "127.0.0.1",
        "port": 6379,
        "auth": null
    }
}
```

usr/share/nginx/html/aeon/config.js

```
var api = "192.168.31.5:8118";

var coinUnits = 1000000000000;

var poolHost = "192.168.31.5";

var irc = "irc.freenode.net/#monero-pools";

var email = "support@cryppit.com";

var cryptonatorWidget = ["AEON-BTC", "AEON-USD""];

var easyminerDownload = "https://github.com/zone117x/cryptonote-easy-miner/rele$

var blockchainExplorer = "http://chainradar.com/AEON/block/";

var transactionExplorer = "http://chainradar.com/aeon/transaction/";

```

## **my start commands**

**(start daemon)**
sudo ./aeond --rpc-bind-ip 192.1.31.5  --rpc-bind-port 9998

**(start wallet rpc)**
sudo ./simplewallet --wallet aeon-pool --pass blablabla --daemon-host 192.168.31.5 --daemon-port 9998 --rpc-bind-port 8082

**(start node)**
sudo node init.js

## **Errors:**

**(init.js screen)**
I have this error:2017-07-24 00:12:04 [pool] (Thread 2) Error polling getblocktemplate {"code":-9,"message":"Core is busy"}

And my pool still on loading but nothing come (look at ss)
![2](https://user-images.githubusercontent.com/7630189/28503003-e48d9d22-7006-11e7-86b2-d274edba7a8d.PNG)
![1](https://user-images.githubusercontent.com/7630189/28503004-e490053a-7006-11e7-9d1f-1231e21ce565.PNG)

**Comment by escreativa** [comment]
I have a similar error. You can look at it here.
Link where you can see the explanation:
[https://github.com/zone117x/node-cryptonote-pool/issues/182](https://github.com/zone117x/node-cryptonote-pool/issues/182)
thanks

**Comment by dinho-afsn** [comment]
Go in the element inspector and see what error is giving, and not enabled cors and is using ipd or different domain in api this occurs. See the error that seems in the console and post here

like
![captura de tela 2017-08-11 as 18 19 25](https://user-images.githubusercontent.com/5239515/29232386-c26e498e-7ec1-11e7-9c8c-0566954a65f9.png)

**Comment by dinho-afsn** [comment]
The api address is wrong

![captura de tela 2017-08-11 as 18 21 33](https://user-images.githubusercontent.com/5239515/29232438-fc6e627c-7ec1-11e7-9d55-5f305656f0f0.png)

![captura de tela 2017-08-11 as 18 21 40](https://user-images.githubusercontent.com/5239515/29232443-00cdbe8a-7ec2-11e7-8a90-a2f23d38f0dd.png)

var api = "192.168.31.5:8118";   wrong

Was thus placed in the API
  "api": {
        "enabled": true,
        "hashrateWindow": 600,
        "updateInterval": 5,
        "port": 8117, <<<<<<<like here
        "blocks": 30,
  "payments": 30,
        "password": "148150"
    },



correct
var api = "192.168.31.5:8117";   correct

Hitting this, your pool will work.
