### ISSUE TITLE
Payments error

### ISSUE THREAD

**Issue by kiraminesupport** [zone117x/node-cryptonote-pool#189]
Hey there, i run an intense mining pool with your pool software

but payments don't going out

i get this error

Error with transfer RPC request to wallet daemon {"code":-4,"message":"Internal node error"}

can anybody help me pls ?

**Comment by kiraminesupport** [comment]
i solved it by my self

**Comment by Thomasmcdaniel9** [comment]
How did you fix issue

**Comment by freemanjackal** [comment]
what did you do??

**Comment by callimmak** [comment]
I have the same error, @x23a1s can you help as pls?? THANKS

**Comment by spotme-main** [comment]
anyone solve this?

**Comment by aejontargaryen** [comment]
what a dick. ha
