### ISSUE TITLE
(Thread 1) Error polling getblocktemplate {"code":-4,"message":"Failed to parse wallet address"}

### ISSUE THREAD

**Issue by igalfsg** [zone117x/node-cryptonote-pool#199]
I am getting this error when I try to run node init.js I am running the wallet RPC and daemon with no problem. Has anyone had this problem?

**Comment by igalfsg** [comment]
jk I cant spell. I misspelled my wallet address ;/ in the config file

**Comment by Jaydeep75** [comment]
I was Same Error: **Failed to parse wallet address**
So any Solution link?
