### ISSUE TITLE
pool not listening on the ports..

### ISSUE THREAD

**Issue by servc4** [zone117x/node-cryptonote-pool#228]
**Hi
My pool is starting witch no errors but listening only on API port**

root@v**********:~/pool# node init.js
2017-11-20 22:01:22 [master] Pool spawned on 1 thread(s)
2017-11-20 22:01:23 [unlocker] Started
2017-11-20 22:01:23 [payments] Started
2017-11-20 22:01:23 [unlocker] No blocks candidates in redis
2017-11-20 22:01:23 [payments] No workers' balances reached the minimum payment threshold
2017-11-20 22:01:23 [charts] Started
2017-11-20 22:01:23 [charts] Started
2017-11-20 22:01:23 [chartsDataCollector] Started
2017-11-20 22:01:23 [api] API started & listening on port 8117

**After some time I have some errors in console..**

TypeError: Cannot read property 'pool' of undefined
    at /root/pool/lib/charts.js:149:30
    at IncomingMessage.<anonymous> (/root/pool/lib/apiInterfaces.js:31:17)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:458:13)

2017-11-20 22:02:23 [master] chartsDataCollector died, spawning replacement...
2017-11-20 22:02:26 [charts] Started
2017-11-20 22:02:26 [chartsDataCollector] Started

**and when I list ports on my server there is no ports 3333, 5555, 7777 like in config and I cant connect to pool by miners.**

**Comment by WeOggy** [comment]
solved?

**Comment by servc4** [comment]
Not really
I use different source from here
[(https://github.com/AcidMiner/forknote-pool)]
I run deamons on two separate VPS like that

./deuterd --rpc-bind-ip 100.100.10.101 --rpc-bind-port 18081
./deuterd --rpc-bind-ip 100.100.10.102 --rpc-bind-port 18081

On first I run also simlewallet like this:

./simplewallet --wallet-file pool.wallet --password password --rpc-bind-port 8082 --daemon-address 100.100.10.101:18081

Both are on Ubuntu 16.04

Now on third VPS on ubuntu 14.04 I run the pool
witch Config of IP's:

"daemon": {
        "host": "100.100.10.101",
        "port": 18081
    },

    "wallet": {
        "host": "100.100.10.101",
        "port": 8082
},

And when simplewallet is on then pool is not listening on mining port like above but when I close simplewallet down the pool is starting as normal there is no errors and pool is working I am able to mine but in pool admin.html simplewallet is down then there is nothing in stats and of course no payments.

**Comment by servc4** [comment]
Hi
I made some changes with IP's
I change them on 0.0.0.0 in run commands of daemons and simlewallet
and I run Pool witch command
node init.js -config=config.json
But the Pool I run before simplewallet and Its looks fine but take a look on screen shots below.
[http://me4u.co/main.jpg](http://me4u.co/main.jpg)
[http://me4u.co/wallet.jpg](http://me4u.co/wallet.jpg)
[http://me4u.co/stats.jpg](http://me4u.co/stats.jpg)

like you see on first one  Total Hashes Submitted: 25384124
But
Pending Balance: 0.000000000000
Total Paid: 0.000000000000

On second one like you see daemon and wallet is ON
On wallet is over 28k

and on third picture you can see stat's
all zeros...
and I don't have Idea why.

**Comment by servc4** [comment]
Sorted...
Answer is hear..
[https://github.com/forknote/forknote-pool/issues/48](https://github.com/forknote/forknote-pool/issues/48)

**Comment by mohs27** [comment]
[]()«‏دوچرخه سوارفول» در مایکت:
https://myket.ir/app/xyz.appmaker.jpowkv
