### ISSUE TITLE
remove denomination

### ISSUE THREAD

**Issue by chpio** [zone117x/node-cryptonote-pool#250]
> With RingCT, denomination does not matter anymore, since amounts are not decomposed in several outputs anymore, so there is no dust problem. Therefore, denomination can be set to 1.

https://monero.stackexchange.com/a/3495

Is denomination still needed for Bytecoin?

**Comment by sebseb7** [comment]
denomination is neccessary for many cryptonote coins. You should not remove it.

**Comment by chpio** [comment]
yeah, you'r right, i thought about making it conditional (disable it only for monero). But i thought there isn't a "guaranteed" way to tell if the current coin is monero, i thought the *coin* config is a user defined value just so you can distinguish multiple installations in a database.

```
/* Used for storage in redis so multiple coins can share the same redis instance. */
"coin": "monero",
```

Now i found out it's been used to determine the coin type by that config value. https://github.com/zone117x/node-cryptonote-pool/blob/a94eeda8f61dc32a6326420ed75e9b032cee2513/lib/pool.js#L54

Would be ok with you if it's disable for monero only?

**Comment by sebseb7** [comment]
you can already effectively disable it by setting it to 1

**Comment by sebseb7** [comment]
"Would it be ok with you if it's disable for monero only?"

it would be ok to disable it for ringct coins, not specifically for monero. The code should have no coin specific hacks.

**Comment by chpio** [comment]
> you can already effectively disable it by setting it to 1
Hmm, yeah i know, but there are still ppl setting it to 0.1XMR ;(

> The code should have no coin specific hacks.

Is there a way to tell if a coin is a ringct coin? I thought about adding a simple list with coin names but that would be coin specific (coin names hardcoded in the code).

**Comment by sebseb7** [comment]
"weil der poolbetreiber immer wieder kurz vor der normalen auszahlung die auszahlgrenze runtergesetzt hat "

das ändert sich aber auch nicht mit irgendwelchen commits.

"Is there a way to tell if a coin is a ringct coin?"

when you can't see the amount in block explorer it's ringct.

http://explorer.havenprotocol.com/tx/f54449a6f9c354ee82f5a280e55d6775b68bb09165f428ece8125a7e7a569be8

"(coin names hardcoded in the code)."

that is a bad practice, because coin charateristics may change. It should be placed in the configuration file, not in the code.

**Comment by chpio** [comment]
> das ändert sich aber auch nicht mit irgendwelchen commits.

aber mit der nächsten installierten version.

> when you can't see the amount in block explorer it's ringct.

i know, i meant to check it in the code, eg quering the the coin daemon.

> that is a bad practice, because coin charateristics may change. It should be placed in the configuration file, not in the code.

dunno about that, you can easily update a hardcoded list by releasing a new version (even an outdated version wouldn't be a real problem in this case), but you can't update a list in an user defined file.

**Comment by bobbieltd** [comment]
Denomination is necessary for all coins ( it is how we pay miners ).
Monero and most Monero’s forks (after Jan 2017) have ringct. Forknote and Bytecoin-based coins don’t have it. (in fact, I’m confused between mixin and ringct. RingCT is an extension of mixin, I guess).
So havenprotocol doesn’t have ringct (it has mixin to hide)

**Comment by sebseb7** [comment]
with ringct you don't need denomination because decimals are no longer decomposited
