### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by tgwaste** [zone117x/node-cryptonote-pool#260]
Hi,
Im not sure how else to ask but can someone please tell me how to obtain the little icons this application uses? I'm working on something for it. Many thanks and sincere apologies for adding this question to Issues.

**Comment by bobbieltd** [comment]
Here is the pool. If you want to have some little coin, download xmrig app (search for xmrig) and mine ETN with your PC.

**Comment by tgwaste** [comment]
Heh.  Im not looking for coins. Im looking for icons.  I can't not find them in the source.

These:  [](http://www.twg.org/files/icons.png)

**Comment by bobbieltd** [comment]
Sorry, misunderstood .

**Comment by nradonicich** [comment]
They come from [Font Awesome](http://fontawesome.io/)

**Comment by tgwaste** [comment]
Many Thanks!
