### ISSUE TITLE
Error when starting pool

### ISSUE THREAD

**Issue by jimbob4842** [zone117x/node-cryptonote-pool#296]
EDIT:

I fixed my original problem (the ports were set incorrectly) but now this happens:

```
instance-3:~/pool$ node init.js -config=config.json
2018-02-23 05:39:20 [master] Pool spawned on 2 thread(s)
2018-02-23 05:39:20 [payments] Started
2018-02-23 05:39:20 [payments] No workers' balances reached the minimum payment threshold
2018-02-23 05:39:20 [unlocker] Started
2018-02-23 05:39:20 [unlocker] No blocks candidates in redis
2018-02-23 05:39:20 [api] API started & listening on port 8117
2018-02-23 05:39:20 [api] Error getting daemon data {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}
2018-02-23 05:39:20 [api] Stat collection finished: NaN ms redis, 30 ms daemon
2018-02-23 05:39:20 [api] Error collecting all stats
2018-02-23 05:39:20 [pool] (Thread 1) Error polling getblocktemplate {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}
2018-02-23 05:39:20 [pool] (Thread 1) Could not start pool
2018-02-23 05:39:20 [pool] (Thread 2) Error polling getblocktemplate {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}
2018-02-23 05:39:20 [pool] (Thread 2) Could not start pool
```

> This is what happens when I try and start the pool
> ```
> @instance-3:~/pool$ node init.js
> 2018-02-23 04:29:03 [master] Redis version check failed
> 
> Error: Ready check failed: Redis connection gone from end event.
>     at RedisClient.on_info_cmd (/home/thepsychoms/pool/node_modules/redis/index.js:380:35)
>     at Command.callback (/home/thepsychoms/pool/node_modules/redis/index.js:430:14)
>     at RedisClient.flush_and_error (/home/thepsychoms/pool/node_modules/redis/index.js:169:29)
>     at RedisClient.connection_gone (/home/thepsychoms/pool/node_modules/redis/index.js:486:10)
>     at Socket.<anonymous> (/home/thepsychoms/pool/node_modules/redis/index.js:114:14)
>     at Socket.emit (events.js:117:20)
>     at _stream_readable.js:944:16
> ```
> and my RPC shows this
> 
> ```
> 2018-02-23 04:29:03.922 [RPC0]  ERROR   net.http        contrib/epee/include/net/http_protocol_handler.inl:303  simple_http_connection_handler::handle_char_out: Error state!!!
> 2018-02-23 04:32:30.297 [RPC0]  ERROR   net.http        contrib/epee/include/net/http_protocol_handler.inl:357  simple_http_connection_handler<t_connection_context>::handle_invoke_query_line(): Failed to match first line: *1
> ```
> 
> Any ideas?
> 
> Also, before this I would get this instead
> ```
> @instance-3:~/pool$ node init.js
> 2018-02-23 03:54:30 [master] Pool spawned on 2 thread(s)
> 2018-02-23 03:54:30 [unlocker] Started
> 2018-02-23 03:54:30 [unlocker] No blocks candidates in redis
> 2018-02-23 03:54:30 [payments] Started
> 2018-02-23 03:54:30 [payments] No workers' balances reached the minimum payment threshold
> 2018-02-23 03:54:30 [api] API started & listening on port 8117
> 2018-02-23 03:54:30 [api] Error getting daemon data {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}
> 2018-02-23 03:54:30 [api] Stat collection finished: NaN ms redis, 15 ms daemon
> 2018-02-23 03:54:30 [api] Error collecting all stats
> 2018-02-23 03:54:36 [api] Stat collection finished: 1 ms redis, 1 ms daemon
> 2018-02-23 03:54:36 [api] Error collecting all stats
> 2018-02-23 03:54:37 [pool] (Thread 2) Error polling getblocktemplate {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}
> 2018-02-23 03:54:37 [pool] (Thread 1) Error polling getblocktemplate {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}
> 2018-02-23 03:54:38 [pool] (Thread 2) Error polling getblocktemplate {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}
> 2018-02-23 03:54:38 [pool] (Thread 1) Error polling getblocktemplate {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}
> 2018-02-23 03:54:39 [pool] (Thread 2) Error polling getblocktemplate {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}
> 2018-02-23 03:54:39 [pool] (Thread 1) Error polling getblocktemplate {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}
> ```

**Comment by zone117x** [comment]
"Redis version check failed"
Install the redis version specified in the instructions.

**Comment by jimbob4842** [comment]
I fixed it by setting the RPC port and IP when launching the daemon. The redis was fine

**Comment by artistgrammer2015** [comment]
how to setting the RPC port and IP
