### ISSUE TITLE
v7 Fork Mods

### ISSUE THREAD

**Issue by alferz** [zone117x/node-cryptonote-pool#317]
Anyone have any idea what needs to change in this repo to support the recent algo change on XMR to v7 Cryptonight?

**Comment by usaflees** [comment]
Was coming to talk about the same thing =[

**Comment by cminatti** [comment]
I notice the author did some changes on the multi-hashing library, (github.com/zone117x/node-multi-hashing) but I don't know if that is all.

**Comment by jbnl** [comment]
When setting my pool package.json to this node-multi-hashing version I can succesfully get through npm update... But when I start the pool I'm seeing an error that I can't solve:

Error: Failed to parse block
    at Object.BlockTemplate.nextBlob (/pool/lib/pool.js:128:23)
    at Object.Miner.getJob (/pool/lib/pool.js:302:41)
    at handleMinerMethod (/pool/lib/pool.js:531:28)
    at handleMessage (/pool/lib/pool.js:660:13)
    at Socket.socket.on.on.on.pushMessage (/pool/lib/pool.js:714:25)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)

Does anyone have an idea how to fix this?

**Comment by cminatti** [comment]
node-multi-hashing and the pool are updated. They work with monero v7 pow. 
@jbnl do #npm list and check you have node-multi-hasning library at the last commit
I have ├─┬ multi-hashing@0.0.9 (git://github.com/zone117x/node-multi-hashing.git#4b77e4ae6603517c571dd11287e959c101cfa9a6)

**Comment by jbnl** [comment]
@cminatti - I see the same commit:

 multi-hashing@0.0.9 (git://github.com/zone117x/node-multi-hashing.git#4b77e4ae6603517c571dd11287e959c101cfa9a6)

**Comment by jbnl** [comment]
The pool starts and as long nobody is connected its fine, but once a miner connects the errors start: Failed to parse block

**Comment by prox443** [comment]
Same issue for me :(

**Comment by dvandal** [comment]
With my code it works fine: https://github.com/dvandal/cryptonote-nodejs-pool

**Comment by alferz** [comment]
Agreed this is no longer an issue, the standard code base works fine with the v7 fork.
