### ISSUE TITLE
Web Frontend cannot connect to api

### ISSUE THREAD

**Issue by acidrs03** [zone117x/node-cryptonote-pool#323]
I have tested trying two scenarios. 
The First scenario is with two servers. 
Server one is running the monero daemon, wallet cli and pool software. Port 8117 for api are open and verified open using a port open check tool externally. This server is running on a home network. 
The pool software runs without any errors.  
Server two is a vps hosting the web frontend. The navbar and pages load without any api data. My var api is set to http://{External ip of home network}:8117

The second scenario is with three servers
Server one is running the monero daemon and wallet cli. This server is running on a home network.
Server two is running the pool software and is able to connect to the daemon and wallet. Port 8117 for api is open and has been checked using open port check tool online. This server is running on AWS ec2 t2.micro
Server three is a vps running the webfront end. Webpage loads blank page with navbar, page is unable to pull api from pool server.

Ive seen many post about this same issue saying that it was fixed just by making sure the api var is set to the external ip of the pool server, but that does not seem to work for me. 
I saw one suggestion to use ssl for api port but no information about how to do that, is it as simple as editing the config.json of the pool server and adding ssl:true to the api section?

I did also try using the scenario of 1 server running everything with apache running the web frontend from the same machine. If i navigate to localhost on the server the webpage and api load without issue. But if i try to load the webpage externally then the same issue happens where no api data is being displayed.

Does anyone have any suggestions i can try or check.

**Comment by acidrs03** [comment]
An Update to my issue. 
Pool is now working with api after a long struggle with getting ssl setup.

**Comment by bruceleeon** [comment]
would you mind sharing how you accomplished ssl with api?

**Comment by acidrs03** [comment]
@bruceleeon 
             
My setup involves the monero daemon and wallet running on one system and the pool software and pool website running on another.

For me to get the ssl working i followed this guide
[https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-16-04](url)

After its installed and running i was able to set the domain name in the api var of config.json for the website files.

The data is being displayed on the website site now but i did run into another issue of the data not being displayed on first visit. i.e going to examplepool.com displays the header bar and the spinning icon. You have to click on another age i.e getting started and then click back to the home page for the data to be displayed. Additionally it doesnt auto refresh and you have to follow these steps each time you want to refresh the data. 

I have another Issue thread started for that, just waiting for some helpful commenter to give me some pointers as to what to check or where i could find the answer.
