### ISSUE TITLE
Don't use this vulnerable for attacks software for public services.

### ISSUE THREAD

**Issue by sammy007** [zone117x/node-cryptonote-pool#88]
Subj. This repo is dead.

**Comment by zone117x** [comment]
I haven't had time to manage this repo. Sammy do you want to take it over?

**Comment by sammy007** [comment]
Not sure I can take it over, I have life too and I will consider this role. I already maintaining my own fork where all hot fixes from me and another people found their place. Please at least merge my master branch.

**Comment by sammy007** [comment]
Not right now, there will be another commit to master soon. So it's necessary to merge them all together.

**Comment by zone117x** [comment]
sammy007 you now have access to control the repo.

**Comment by zone117x** [comment]
You rock @sammy007 !
